version: '3.4'

networks:
  gsheettelegrambotapp:

services:
  gsheettelegrambot.db:
    container_name: gsheet-telegrambot-db
    image: mcr.microsoft.com/mssql/server:2019-latest 
    volumes:
      - ./mssqldb:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD} 
    networks:
      - gsheettelegrambotapp
  
  gsheettelegrambot.web:
    env_file: 
      - .env
    container_name: gsheet-telegrambot-web
    image: valeriynashchokin/gsheettelegrambotweb:latest
    build:
      context: .
      dockerfile: GSheetTelegramBot.Web/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - gsheettelegrambot.db
    environment:
      - DB_HOST=gsheettelegrambot.db
      - DB_NAME=GsheetTelegramBotDB
    networks:
      - gsheettelegrambotapp
